### PR TITLE
[FIX-440] Correct repository name bug

### LINKED ISSUE #440: ActionView::Template::Error: undefined method `name' for nil:NilClass

              contribution.repository.name
                                     ^^^^^
View details in Rollbar: [https://rollbar.com/punchlock/punchlock/items/181/](https://rollbar.com/punchlock/punchlock/items/181/)

```

NoMethodError: undefined method `name' for nil:NilClass

              contribution.repository.name
                                     ^^^^^
  File "/app/app/admin/user.rb", line 214, in block (7 levels) in <main>
  File "/app/vendor/bundle/ruby/3.1.0/gems/activeadmin-2.13.1/lib/active_admin/view_helpers/display_helper.rb", line 66, in find_value
  File "/app/vendor/bundle/ruby/3.1.0/gems/activeadmin-2.13.1/lib/active_admin/view_helpers/display_helper.rb", line 53, in format_attribute
  File "/app/vendor/bundle/ruby/3.1.0/gems/activeadmin-2.13.1/lib/active_admin/views/components/table_for.rb", line 103, in block in build_table_cell
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/element/builder_methods.rb", line 32, in block in build_tag
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/context.rb", line 94, in with_current_arbre_element
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/element/builder_methods.rb", line 50, in with_current_arbre_element
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/element/builder_methods.rb", line 27, in build_tag
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/element/builder_methods.rb", line 40, in insert_tag
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/element/builder_methods.rb", line 15, in td
  File "/app/vendor/bundle/ruby/3.1.0/gems/activeadmin-2.13.1/lib/active_admin/views/components/table_for.rb", line 102, in build_table_cell
  File "/app/vendor/bundle/ruby/3.1.0/gems/activeadmin-2.13.1/lib/active_admin/views/components/table_for.rb", line 46, in block (2 levels) in column
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/context.rb", line 94, in with_current_arbre_element
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/element/builder_methods.rb", line 50, in with_current_arbre_element
  File "/app/vendor/bundle/ruby/3.1.0/gems/activeadmin-2.13.1/lib/active_admin/views/components/table_for.rb", line 45, in block in column
  File "/app/vendor/bundle/ruby/3.1.0/gems/draper-4.0.2/lib/draper/delegation.rb", line 10, in each
  File "/app/vendor/bundle/ruby/3.1.0/gems/draper-4.0.2/lib/draper/delegation.rb", line 10, in each_with_index
  File "/app/vendor/bundle/ruby/3.1.0/gems/draper-4.0.2/lib/draper/delegation.rb", line 10, in each_with_index
  File "/app/vendor/bundle/ruby/3.1.0/gems/activeadmin-2.13.1/lib/active_admin/views/components/table_for.rb", line 44, in column
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/element.rb", line 179, in method_missing
  File "/app/app/admin/user.rb", line 213, in block (6 levels) in <main>
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/element/builder_methods.rb", line 32, in block in build_tag
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/context.rb", line 94, in with_current_arbre_element
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/element/builder_methods.rb", line 50, in with_current_arbre_element
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/element/builder_methods.rb", line 27, in build_tag
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/element/builder_methods.rb", line 40, in insert_tag
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/element/builder_methods.rb", line 15, in table_for
  File "/app/app/admin/user.rb", line 212, in block (5 levels) in <main>
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/element/builder_methods.rb", line 32, in block in build_tag
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/context.rb", line 94, in with_current_arbre_element
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/element/builder_methods.rb", line 50, in with_current_arbre_element
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/element/builder_methods.rb", line 27, in build_tag
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/element/builder_methods.rb", line 40, in insert_tag
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/element/builder_methods.rb", line 15, in panel
  File "/app/app/admin/user.rb", line 211, in block (4 levels) in <main>
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/element/builder_methods.rb", line 32, in block in build_tag
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/context.rb", line 94, in with_current_arbre_element
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/element/builder_methods.rb", line 50, in with_current_arbre_element
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/element/builder_methods.rb", line 27, in build_tag
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/element/builder_methods.rb", line 40, in insert_tag
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/element/builder_methods.rb", line 15, in div
  File "/app/vendor/bundle/ruby/3.1.0/gems/activeadmin-2.13.1/lib/active_admin/views/components/tabs.rb", line 29, in build_content_item
  File "/app/vendor/bundle/ruby/3.1.0/gems/activeadmin-2.13.1/lib/active_admin/views/components/tabs.rb", line 10, in tab
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/element.rb", line 179, in method_missing
  File "/app/app/admin/user.rb", line 192, in block (3 levels) in <main>
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/element/builder_methods.rb", line 32, in block in build_tag
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/context.rb", line 94, in with_current_arbre_element
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/element/builder_methods.rb", line 50, in with_current_arbre_element
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/element/builder_methods.rb", line 27, in build_tag
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/element/builder_methods.rb", line 40, in insert_tag
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/element/builder_methods.rb", line 15, in tabs
  File "/app/app/admin/user.rb", line 83, in block (2 levels) in <main>
  File "/app/vendor/bundle/ruby/3.1.0/gems/activeadmin-2.13.1/lib/active_admin/views/pages/show.rb", line 22, in instance_exec
  File "/app/vendor/bundle/ruby/3.1.0/gems/activeadmin-2.13.1/lib/active_admin/views/pages/show.rb", line 22, in main_content
  File "/app/vendor/bundle/ruby/3.1.0/gems/activeadmin-2.13.1/lib/active_admin/views/pages/base.rb", line 104, in block (2 levels) in build_main_content_wrapper
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/element/builder_methods.rb", line 32, in block in build_tag
  File "/app/vendor/bundle/ruby/3.1.0/gems/arbre-1.5.0/lib/arbre/context.rb", line 94, in with_current_arbre_element

### PR DESCRIPTION
**Pull request by JonasTeixeira42**
This PR closes #440 

- it correct the repository name when there is no repository
image

### CODE REVIEW

File: app/models/repository.rb [hunk 1]
```diff
@@ -6,4 +6,8 @@ class Repository < ApplicationRecord
   def to_s
     link
   end
+
+  def name
+    self.decorate.name
+  end
```
Comment (adbatista) [inline app/models/repository.rb:12]: this should no be in the model, the idea of a decorator is to decorate the original method
