### PR TITLE
fix: Add links of contributions to e-mail description

### LINKED ISSUE #535: Contribution email doesn't list PRs to give description
When a user receive an email about his contribution, isn't possible to identify the PRs. Because the email only show the quantity of PRs that needs description.

### Expected behavior
Besides the quantity of PRs, the users needs to know which contribution is being mentioned to give proper description.

### PR DESCRIPTION
**Pull request by ramos-ph**
This PR changed the e-mail referring to PRs without description to include the links to Punchclock, instead of not specifying any of the required PRs.

image

Fixes #535

### CODE REVIEW

File: app/jobs/alert_fill_contribution_description_job.rb [hunk 1]
```diff
@@ -3,10 +3,14 @@ class AlertFillContributionDescriptionJob < ApplicationJob
...
     user = User.find(user_id)
-    contributions = user.contributions.received 
+    contributions = user.contributions.received.without_description
 
     unless contributions.empty?
-      NotificationMailer.notify_fill_contribution_description(user, contributions.length).deliver_later
+      NotificationMailer.notify_fill_contribution_description(
+        user: user,
+        contributions_total: contributions.length,
+        contributions_links: contributions.pluck(:id, :link)
```
Comment (adbatista) [inline app/jobs/alert_fill_contribution_description_job.rb:12]: here you have the relation `contributions`, and you call, length, and pluck, you will end up hitting the db twice

an approach to avoid this would be

```suggestion
        contributions_total: contributions.length,
        contributions_links: contributions.map { [_1.id, _1.link] }
```

or 

```suggestion
        contributions_link = contributions.pluck(:id, :link)
        contributions_total: contributions_link.lenth,
        contributions_links: contributions_link
```

File: spec/mailers/notification_mailer_spec.rb [hunk 2]
```diff
@@ -253,7 +253,14 @@
     context 'when notify user to fill contribution description' do
       let(:user) { create(:user) }
       let!(:contributions) { FactoryBot.create_list(:contribution, 5, user: user) }
-      let(:mail) { NotificationMailer.notify_fill_contribution_description(user, contributions.length) }
+      let(:mail) do
+        NotificationMailer
+          .notify_fill_contribution_description(
+            user:,
+            contributions_total: contributions.length,
+            contributions_links: contributions.pluck(:id, :link)
```
Comment (adbatista) [inline spec/mailers/notification_mailer_spec.rb:261]: same here, you can avoid hitting the db twice, the tests will run faster

File: app/jobs/alert_fill_contribution_description_job.rb (hunk 1 above)
Comment (ramos-ph) [reply app/jobs/alert_fill_contribution_description_job.rb]: Fixed it! Ty

**Review by adbatista — APPROVED** [review]
